Bugfix: Linux is case sensitive - Include Arduino.h instead of arduino.h
While compiling with Arduino (1.8.5) at Ubuntu (17.10) I get the error below:

In file included from <home dir>/Arduino/libraries/Itho/CC1101.h:9:0,
                 from <home dir>/Arduino/libraries/Itho/IthoCC1101.h:9,
                 from <home dir>/IthoEcoFanRFT/Master/IthoEcoFanRFT/IthoEcoFanRFT.ino:28:
<home dir>/Arduino/libraries/Itho/CC1101Packet.h:10:21: fatal error: arduino.h: No such file or directory
 #include <arduino.h>
                     ^
compilation terminated.
exit status 1
Error compiling for board WeMos D1 R2 & mini.

Signed-off-by: Vincent de Groot <git@videgro.net>